# Generated by Django 5.0.4 on 2024-06-24 05:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
        migrations.DeleteModel(
            name='Message',
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
