# Generated by Django 5.0.4 on 2024-06-24 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0009_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ('timestamp',)},
        ),
    ]
